title: KL3 
author: Kevin Lu 
email: lu3kevin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal github website for lazy stuff by a lazy person.

# social links
twitter_username: your-twitter-handle
github_username:  KL3

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
